// JsFromRoutes CacheKey a95b79cc37d0f9416badcd94d956cfa1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as home } from './HomeApi'
export { default as apiPosts } from './Api/PostsApi'
export { default as apiComments } from './Api/CommentsApi'
