// JsFromRoutes CacheKey 43cca38d6665d3571c1fa6f533f97223
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/posts'),
  create: /* #__PURE__ */ definePathHelper('post', '/posts'),
  new: /* #__PURE__ */ definePathHelper('get', '/posts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/posts/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/posts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/posts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/posts/:id'),
}
