// JsFromRoutes CacheKey 834a35d4b27160c4734e1c337715e6c9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/comments'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/comments'),
  new: /* #__PURE__ */ definePathHelper('get', '/api/comments/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/comments/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/comments/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/comments/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/comments/:id'),
}
