// JsFromRoutes CacheKey ed97745772d1976f74397050a002829d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/api/posts'),
  create: /* #__PURE__ */ definePathHelper('post', '/api/posts'),
  new: /* #__PURE__ */ definePathHelper('get', '/api/posts/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/api/posts/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/api/posts/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/api/posts/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/api/posts/:id'),
}
